<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Orders_nav-cart-icon nav-sprite</name>
   <tag></tag>
   <elementGuidId>5bec4c52-7d53-483f-b161-2eaa53f089b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-cart-count-container']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.nav-cart-icon.nav-sprite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2995bb6f-1e44-4ad2-9845-373fe97c8edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-cart-icon nav-sprite</value>
      <webElementGuid>dc7625bc-5d72-4a96-8c23-119b7cc57e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-cart-count-container&quot;)/span[@class=&quot;nav-cart-icon nav-sprite&quot;]</value>
      <webElementGuid>877f6cee-00c7-4c93-8134-11fca5959877</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-cart-count-container']/span[2]</value>
      <webElementGuid>b95c8830-9093-43a4-a1b8-7e449aaaade6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/span[2]</value>
      <webElementGuid>d92dba3a-18ce-4acf-9756-726f73fe20c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
