<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hello, Gnaneshwari</name>
   <tag></tag>
   <elementGuidId>0d93e62c-c71b-4203-af22-8889b8c03558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='nav-link-accountList-nav-line-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-link-accountList-nav-line-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>670ecd41-0cc2-4a05-9862-2c36b1918de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-link-accountList-nav-line-1</value>
      <webElementGuid>086d52f5-e57f-427b-98c8-ac7cc3db6649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-line-1 nav-progressive-content</value>
      <webElementGuid>cb9bf1cb-4c2b-4bc1-a5ec-0e9225b51902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello, Gnaneshwari</value>
      <webElementGuid>83be7da0-69c4-4a07-939c-18d69e194cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-link-accountList-nav-line-1&quot;)</value>
      <webElementGuid>0179b371-e157-4f42-bc30-c6984126f2ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='nav-link-accountList-nav-line-1']</value>
      <webElementGuid>e2426e7f-9f37-4fab-bb5f-02b257f2c803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-link-accountList']/div/span</value>
      <webElementGuid>f01cff7b-e214-4a62-85c7-1d9aaeb469c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::span[2]</value>
      <webElementGuid>372194bb-59cc-4752-be4d-cb31fcbad7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Amazon.in'])[1]/following::span[7]</value>
      <webElementGuid>e236b29d-5c98-403c-b261-c2daea56b7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account &amp; Lists'])[1]/preceding::span[1]</value>
      <webElementGuid>42011ea4-541a-47e2-b2f0-f3b0bc6d15d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Gnaneshwari? Sign Out'])[1]/preceding::span[3]</value>
      <webElementGuid>9f465a0a-75b2-414d-a167-876a9e9817de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hello, Gnaneshwari']/parent::*</value>
      <webElementGuid>7d8e6b96-e6a0-4039-81e4-c320e5b9e7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>635dfc38-3daa-4ca6-9e83-a45affeb9586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'nav-link-accountList-nav-line-1' and (text() = 'Hello, Gnaneshwari' or . = 'Hello, Gnaneshwari')]</value>
      <webElementGuid>13b823f9-b2bf-4672-aa87-2711e5bbff69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
